### ISSUE TITLE
AssertionError: LRI not allowed here

### ISSUE THREAD

**Issue by amirarj** [alihoseiny/word_cloud_fa#6]
**Describe the bug**
got this error while generating wordcloud from txt file.

**To Reproduce**
```
LRI not allowed here
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/pyrogram/client/ext/dispatcher.py", line 199, in update_worker
    handler.callback(self.client, *args)
  File "main.py", line 37, in hello
    wc = wodcloud.generate(text)  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/wordcloud_fa/WordCloudFa.py", line 175, in generate
    return self.generate_from_text(text)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 601, in generate_from_text
    self.generate_from_frequencies(words)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/wordcloud_fa/WordCloudFa.py", line 161, in generate_from_frequencies
    words = WordCloudFa.reshape_words(words)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/wordcloud_fa/WordCloudFa.py", line 75, in reshape_words
    return get_display(arabic_reshaper.reshape(combined_words)).split("\n")
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/bidi/algorithm.py", line 648, in get_display
    resolve_implicit_levels(storage, debug)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.8/site-packages/bidi/algorithm.py", line 465, in resolve_implicit_levels
    assert _ch['type'] in ('L', 'R', 'EN', 'AN'),\
AssertionError: LRI not allowed here
```

**Comment by alihoseiny** [comment]
Thank for your report. It seems that you have some strange characters in your input text and your problem is the same as [this issue](https://github.com/alihoseiny/word_cloud_fa/issues/3).
We will cover bad characters removal in the next release. But for now, you can fix that problem by calling the below code on your data before passing them in the `WordCloudFa` methods.
```
eridPatterns = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               u"\U0001f926-\U0001f937"
                               u'\U00010000-\U0010ffff'
                               u"\u200d"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\u3030"
                               u"\ufe0f"
                               u"\u2069"
                               u"\u2066"
                               u"\u200c"
                               u"\u2068"
                               u"\u2067"
                               "]+", flags=re.UNICODE)
    clean_text = weridPatterns.sub(r'', raw_text)
```
