### ISSUE TITLE
[BUG] wrong argument passed to function

### ISSUE THREAD

**Issue by mohebz** [alihoseiny/word_cloud_fa#8]
Hi,

**Describe the bug**
Tried to run one of the examples (english-example.py) when I got the following error

**Screenshots**
![Screenshot from 2020-05-20 20-07-44](https://user-images.githubusercontent.com/26295746/82466606-e477f600-9ad5-11ea-9906-05fea0b0fec3.png)

**Possible Fix**
```
        if self.collocations:
            word_counts = unigrams_and_bigrams(words, self.normalize_plurals)
        else:
            word_counts, _ = process_tokens(words, self.normalize_plurals)

        return word_counts
```
The second argument passed to *unigrams_and_bigrams* function (line 134 WordCloudFa.py) is *self.normalize_plurals* by mistake. Changing it to *self.stopwords* seems to fix it.

**Comment by alihoseiny** [comment]
Thanks for your report. I will fix it.

**Comment by mrazavim** [comment]
`<class 'str'>
Traceback (most recent call last):
  File "C:/Users/Aerospace/Desktop/My Projects/word_cloud/Persian/persian.py", line 14, in <module>
    frequency=wc.process_text(text)
  File "C:\Program Files\python\lib\site-packages\wordcloud_fa\WordCloudFa.py", line 134, in process_text
    word_counts = unigrams_and_bigrams(words, self.normalize_plurals)
  File "C:\Users\Aerospace\AppData\Roaming\Python\Python38\site-packages\wordcloud\tokenization.py", line 42, in unigrams_and_bigrams
    bigrams = list(p for p in pairwise(words) if not all(w in stopwords for w in p))
  File "C:\Users\Aerospace\AppData\Roaming\Python\Python38\site-packages\wordcloud\tokenization.py", line 42, in <genexpr>
    bigrams = list(p for p in pairwise(words) if not all(w in stopwords for w in p))
  File "C:\Users\Aerospace\AppData\Roaming\Python\Python38\site-packages\wordcloud\tokenization.py", line 42, in <genexpr>
    bigrams = list(p for p in pairwise(words) if not all(w in stopwords for w in p))
TypeError: argument of type 'bool' is not iterable

**Comment by MehdiMoosavi88** [comment]
> Thanks for your report. I will fix it.

I have the same error
Did you fix it?
Thanks.

**Comment by alihoseiny** [comment]
Hello. I am working on it.

**Comment by MehdiMoosavi88** [comment]
Good luck!

**Comment by tadbirkesht93** [comment]
I have the same error

**Comment by alihoseiny** [comment]
Hi folks. I fixed the issue. Please update to the 0.1.8 version.
